network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp4: false
      addresses:
          - 192.168.0.11/24
      routes:
          - to: default
            via: 192.168.0.1
      nameservers:
          addresses:
              - 192.168.0.1
